const mongoose = require("mongoose");

const meetingSchema = new mongoose.Schema(
    {
        // MongoDB user who owns this meeting
        userId: {
            type: mongoose.Schema.Types.ObjectId,
            ref: "User",
            required: true
        },

        // Meeting title shown in the UI
        title: {
            type: String,
            required: true,
            trim: true
        },

        // Source type
        sourceType: {
            type: String,
            enum: ["youtube", "upload"],
            required: true
        },

        // YouTube URL or uploaded file reference
        source: {
            type: String,
            required: true
        },

        // Meeting language
        language: {
            type: String,
            enum: ["english", "hinglish"],
            default: "english"
        },

        // -----------------------------------------
        // AI / RAG IDENTIFIER
        // -----------------------------------------
        // This is the meeting ID generated by
        // the Python AI pipeline.
        //
        // Example:
        // e2d8b6b99e5d
        //
        // Python uses this ID to create the ChromaDB
        // collection:
        //
        // meeting_e2d8b6b99e5d
        //
        aiMeetingId: {
            type: String,
            default: ""
        },

        // -----------------------------------------
        // AI RESULTS
        // -----------------------------------------

        transcript: {
            type: String,
            default: ""
        },

        summary: {
            type: String,
            default: ""
        },

        actionItems: {
            type: String,
            default: ""
        },

        keyDecisions: {
            type: String,
            default: ""
        },

        openQuestions: {
            type: String,
            default: ""
        },

        // -----------------------------------------
        // PROCESSING STATUS
        // -----------------------------------------

        status: {
            type: String,
            enum: ["processing", "completed", "failed"],
            default: "processing"
        }
    },
    {
        timestamps: true
    }
);

const Meeting = mongoose.model(
    "Meeting",
    meetingSchema
);

module.exports = Meeting;